import { Toaster } from "@/components/ui/sonner" // Client component
import { SWRProvider } from "@/fetchSwr/swrProvider"
import { brandName } from "@/utils"
import Provider from "@/utils/session" // Client provider
import { Analytics } from '@vercel/analytics/next'
import { NextIntlClientProvider } from "next-intl" // Client provider
import { getLocale, getMessages } from "next-intl/server"
import { Inter } from "next/font/google"
import "swiper/css"
import "swiper/css/autoplay"
import "swiper/css/navigation"
import "swiper/css/pagination"
import "./global.css"

const inter = Inter({
	weight: ["300", "400", "500", "600", "700"],
	subsets: ["latin"],
})

export const metadata = {
	title: `${brandName} - Full Stack Recruitment Hiring Management Next.js Application`,
	description: "Generated by create next app",
	icons: {
		icon: [
			{ url: "/favicon.ico", sizes: "any" },
			{ url: "/icon.svg", type: "image/svg+xml" },
		],
		apple: { url: "/apple-icon.png", sizes: "180x180" },
	},
}

export default async function RootLayout({ children }) {
	// Fetch locale and messages
	const locale = await getLocale()
	const messages = await getMessages(locale)

	// Default theme: Dark (you can replace this with user preference logic)
	const isDarkMode = true

	return (
		<html
			lang={locale}
			className={isDarkMode ? "dark" : "light"}
			style={{ colorScheme: isDarkMode ? "dark" : "light" }}
		>
			<body className={`${inter.className}`}>
				<SWRProvider>
					<NextIntlClientProvider messages={messages}>
						<Provider>
							{/* Toaster is a client component */}
							<Toaster richColors position="top-right" />
							{children}
							<Analytics />
						</Provider>
					</NextIntlClientProvider>
				</SWRProvider>
			</body>
		</html>
	)
}

